#define MIDI_CHANNEL 1

#define MIDI_NOTE_FORWARD 43
#define MIDI_NOTE_BACKWARD 45
#define MIDI_NOTE_HIT 47
#define MIDI_NOTE_PIEZO_FRONT 36
#define MIDI_NOTE_PIEZO_BACK 38

#define NOTE_FORWARD 0
#define NOTE_BACKWARD 1
#define NOTE_HIT 2
#define NOTE_PIEZO_FRONT 3
#define NOTE_PIEZO_BACK 4
#define NOTE_OFF 5

// SENSOR_BEGIN
#define SENSORREAD_ACCEL_X 0
#define SENSORREAD_ACCEL_Y 1
#define SENSORREAD_PIEZO_FRONT 2
#define SENSORREAD_PIEZO_BACK 3

#define SENSOR_PIEZO_FRONT_ANALOG 0
#define SENSOR_PIEZO_BACK_ANALOG 1

#define BUFFER_SIZE 8

#define RESOLUTION 1

// SmoothFilter Samples
#define SMOOTH_FILTER 11





#define NOTE_RELEASE_FORWARD 100
#define NOTE_RELEASE_BACKWARD -100
#define NOTE_RELEASE_HIT 100
#define NOTE_RELEASE_PIEZO_FRONT 30
#define NOTE_RELEASE_PIEZO_BACK 30

#define NOTE_THRESHOLD_FORWARD 600
#define NOTE_THRESHOLD_BACKWARD -400
#define NOTE_THRESHOLD_HIT 550
#define NOTE_THRESHOLD_PIEZO_FRONT 50
#define NOTE_THRESHOLD_PIEZO_BACK 50

#define CAN_HIT_THRESOLD 30

////////PIEZO///////
// SENSOR_BEGIN
#define A_NotaAdelante 0
#define A_NotaAtras 1
#define A_PIEZO_ADELANTE 0
#define A_PIEZO_ATRAS 1
// SENSOR_END
#define SMOOTH_SAMPLES 15
#define PIEZO_SMOOTH_SAMPLES 5